### ISSUE TITLE
re-organize Google Drive

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva#12]
Here's a first crack at re-organizing the Drive. Thinking we have three buckets:
1. Admin
2. Projects/Research
3. Notes/Meetings

What do you think? Probably requires a few currently existing folders to be renamed. The goal is to start putting some of our research into project-specific folders so we can have it all in one place. That's what makes sense to me, but if it doesn't to you this is definitely open for critique!

```
Team Admin * 
  | - Coding Guidelines
  | - Contacts
  | - Blog
  | - Travel Budget *
  | - etc...

Projects & Research *
  | - Build Week
  | - Code Across
  | - Financial Verification
  | - Services List
  | - Data  
  | - Design  
  | - Ideas
  | - Research

Meetings & Notes * 
  | - Lecture Notes
  | - Meetings
  | - Presentations
  | - Templates
  | - User Interviews
  | - Daily Check-ins
```

**Comment by bengolder** [comment]
Thanks for taking initiative on this. Personally, I'd rather aim to reduce the total number of folders instead of adding a new layer. But I like the simplicity of your top layer. Could we eliminate/combine/archive more folders or files? Could file-renaming make things easier to find without adding new folders? Just thinking.

**Comment by mapsam** [comment]
Good point! I like that. It seems that we could triage all of the research into their own projects as a first step. There is probably no need for "lecture notes" or "presentations" in the `/meetings & notes` folder since they are fairly empty.

What about `/ideas` folder? It feels pretty vague to me right now.

**Comment by bengolder** [comment]
Yeah, if we don't have a strong reason to keep a folder, I say scrap it. We can combine "ideas"-type stuff into design if we want. I imagine design to be a place that can hold ideas/sketches/lists/needs that we've thought about.

**Comment by mapsam** [comment]
Okay cool - here's an updated structure:

```
Team Admin * 
  | - Contacts
  | - Blog
  | - Travel Budget *
  | - RVA Presentations
  | - etc...

Projects & Research *
  | - Build Week
  | - Code Across
  | - Financial Verification
  | - Services List
  | - Data
  | - Design & Ideas
     | - User Interviews

Meetings & Notes * 
  | - Meetings & lecture notes (organized by month?)
  | - Daily Check-ins (also organized by month?)

ARCHIVE
  | - Templates
```

is that fewer? removed `coding guidelines` since it's just a single file that can live under `/admin`

**Comment by mapsam** [comment]
```
Team Admin * 
  | - Contacts
  | - Blog
  | - Travel Budget *
  | - RVA Presentations
  | - etc...

Projects & Research *
  | - Build Week
  | - Code Across
  | - Financial Verification (all 'design' goes into this)
  | - Services List
  | - Data
  | - User Interviews

Meetings & Notes * 
  | - Meetings & lecture notes (organized by month?)
  | - Daily Check-ins (also organized by month?)

ARCHIVE
  | - Templates
```

**Comment by mapsam** [comment]
Complete! Final decision after our weekly check-in was to use the above template, but move our most used projects to the root level directory for quick access. New root level directories are as follows:

```
Admin
Research
Meetings & Notes
Financial Verification (project)
Services List (project)
_Archive
```
