### ISSUE TITLE
Set up Mail Chimp account for contacts to keep them in the loop

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva#17]
I'm interested in hearing your thoughts on setting up a quick email campaign process for sending updates to our contacts. I see it particularly useful for a couple reasons:
- sharing our write-ups and project updates through rva.codeforamerica.org
- letting people know when we are returning, which allows us to potentially set up "happy hours" or more general "let's hang out" sessions with people in advance where it's more of a walk-in kind of meeting.

People would be able to forward and unsubscribe, so shouldn't be too invasive.

cc/ @esmithayer & @bengolder

**Comment by mapsam** [comment]
Team Miami-Dade has one set up [here](http://us2.campaign-archive2.com/?u=d9acf2a4c694efbd76a48936f&id=1f216e214a&e=6c9e1dac8d). I wonder if @mathias-gibson, @ErnieAtLYD, or @phiden would mind chiming in to hear if they've had positive feedback from this?

**Comment by phiden** [comment]
We've had pretty great success and no negative feedback, so I'd say go for it. Mailchimp has built-in unsubscribe, and of 140ish people on the list we've only had two unsubscribes in three weeks. Also, ping Zoe -- she had some great advice for us last week and is happy to share!

**Comment by mapsam** [comment]
Great! Thanks @phiden. That's good to hear about the unsubscribes - seems like there's way more benefit than downsides here. How often are you sending them?

**Comment by phiden** [comment]
We send them once a week, on Mondays.

**Comment by mapsam** [comment]
Terrific. Muchas gracias señorita!

**Comment by ErnieAtLYD** [comment]
The only thing I would add is that for our very first newsletter, we had a sentence "You're receiving this mailing list because [we interviewed with February.]" I think that helps reduce any potential confusion.

**Comment by mapsam** [comment]
This is complete. We sent our first email two weeks ago. Great success! Just pushed some additions in 993a3c050eee425c40a82f631dddb2e7aa687cf2 while working on #18 that include an email signup form button for people to subscribe
