### ISSUE TITLE
March process post

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva#18]
Starting the thread about the march post. @esmithayer put together a great first draft!

**Comment by mapsam** [comment]
I've put together photos for most of the prompts in your first draft, @esmithayer. Here they are: 

```
[header photo: giant wall of post-its/drawings/etc]
```

![header_march_process](https://cloud.githubusercontent.com/assets/1943001/7052557/354588e0-dde4-11e4-8226-c6048f808543.jpg)

```
[pictures of some sketches, maybe with the pencil->ink steps and/or post-its on them]
```

![march_process_sketches](https://cloud.githubusercontent.com/assets/1943001/7052563/42dd1afe-dde4-11e4-8d9a-2e9f0a901744.jpg)

```
[picture of sketch of patient gathering documents] 
```

![looking-for-docs](https://cloud.githubusercontent.com/assets/1943001/7052573/542b3426-dde4-11e4-9e82-b30eb217abdd.png)

```
[gif of resource list autocomplete]
```

![searchable-services-example](https://cloud.githubusercontent.com/assets/1943001/7052579/5f611810-dde4-11e4-9624-b9eba6e7c487.gif)

**I don't have a photo for this one though!**

```
[picture of one of the How Might We brainstorms.  Or maybe some of those brainstorm prompt cards we got could be cool too?]
```

I also added an extra `<aside>` photo for the financial screening of some post-its. Just a little extra:
![screen shot 2015-04-08 at 11 43 57 am](https://cloud.githubusercontent.com/assets/1943001/7052615/9bbbd034-dde4-11e4-82ac-94e02180e7b2.png)

**Comment by mapsam** [comment]
Confirmed that we will use this image:

![march_process-howmightwe](https://cloud.githubusercontent.com/assets/1943001/7122298/686e870a-e1cf-11e4-99fe-bff5578d57dc.jpg)

**Comment by bengolder** [comment]
I didn't notice that we were including the How Might We exercise until just now. I left a comment about it on the blog google doc. Not sure that this is the best topic and picture to include about process unless we give a bit more context.

**Comment by bengolder** [comment]
I should also note that I have quite a few pictures of the sketching process if you need any more.

**Comment by mapsam** [comment]
If you have any photos that you think would best replace any of the above definitely send them my way!

**Comment by esmithayer** [comment]
I was planning to use the "feedback on police interactions" photo when I wrote the post. Was that from Team Indy or Vallejo? I think this screening culture one would be a little misleading--it's not really what we've been focusing on.

**Comment by mapsam** [comment]
Terrific. In terms of using an actual pathway to replace the `[pictures of some sketches, maybe with the pencil->ink steps and/or post-its on them]` photo, here's an example of them in a "storyboard" format. Any thoughts on doing something like this? _Note: the actual pathway can be different, just grabbed images for the sake of example._

![pathways](https://cloud.githubusercontent.com/assets/1943001/7127567/eec4f340-e1fa-11e4-83e5-9f79e1c1e917.jpg)

**Comment by mapsam** [comment]
Alright, with a new photo from Ben this morning here's the updated full-width image:

![screen shot 2015-04-15 at 6 35 31 pm](https://cloud.githubusercontent.com/assets/1943001/7172532/4c6d7a4a-e39e-11e4-869f-22134a918c0e.png)
