### ISSUE TITLE
How do we capture data if there is no sharing action?

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva#27]
We have decided to continue development/design under the idea of "umbrella consent", which means a patient is visible to any clinic using the app. If we remove the need to _share a patient_ we also lose the ability to record that action in the database. This means we can no longer show _where_  a patient has been in past, but this is an important feature ... how do we capture this information now?

**Comment by esmithayer** [comment]
We should find out how the Fairfax application handles this, but a couple things I can think of:
1. Show edits to patient's info (like we already are) as well as who has viewed a patient. Probably kind of confusing.
2. Have a section on the patient details page where screening staff inputs something like "yes, patient was screened here and is on sliding scale C"
3. Leave the sharing buttons in, but instead of a click causing a new organization to get access, it just means that the organization gets some sort of notification that someone was referred to them. Not totally sure what this would mean--would the receiving organization consider that a submitted application and follow up without the patient taking further action?

**Comment by mapsam** [comment]
1. I think we should still show edits to a patient's information, this will keep specific users attached to patients, which could be helpful for making contact in the future. Showing views could be a separate type of "event" that we could filter in or out if necessary.
2. I'd be interested to see if clinics would use the "yes we've seen this patient" portion - it kind of feels like we'd be forcing the desire for that information, and we couldn't rely on it being 100% accurate since people could easily not press it.
3. I like the idea of the latter part, at least being able to send notifications to another clinic about a patient. I wonder if we could include a text field that someone fills out for sending those notifications - then they'd have a bit more meaning and would cover any edge cases if we just let the referrers say why they are sending the information.

**Comment by bengolder** [comment]
1. Yes. It should take on more than one appearance in the UI. (#24)
2. Yes we should definitely have this. It should help to facilitate communication between the navigator and the screener. We should record responses and non-responses. No response is data. There should be a way for screeners to give feedback (approval, approval for sliding scale, denial with comments, conditional approval).
3. Yes. Definitely. Example: Camila finishes a screening for Tulip and is looking at eligibility results. She should be able to hit a button that sends an email to Bryan, the screener at Daily Planet. If Bryan happens to view the splash page on his own, he should also see a notification there about Tulip's application.  Bryan should be able to click on a link in the email that takes him to Tulip's info and estimated eligibility. On this page with Tulip's info, there should be a way for Bryan to give feedback (approval, approval for sliding scale, denial with comments, conditional approval).

**Comment by mapsam** [comment]
:+1: for showing patient **edit history**

:+1: for **sharing**, which includes notifications

:+1: for **patient visit button** that allows a clinic to confirm they have seen a patient

**Comment by mapsam** [comment]
Consensus on showing patient edit history. :dancer: Check this out in codeforamerica/rva-screening-ui-prototypes/issues/28 or codeforamerica/rva-screening-ui-prototypes/issues/27

Thinking that we won't collect "who has viewed this patient" until it comes up and is requested since the information doesn't tell us much.

Two things moving forward when it comes to sharing a patient:
1. When a navigator refers a patient, the recipient gets an email with a unique URL and a notification in the app saying there is a new patient referral.
2. A navigator/case manager/clinic worker can also go to patient details and click a button/fill out a form that entails "patient has been approved to see appointments at this clinic" or even more granular, "patient is on sliding scale B at this clinic"

**Comment by mapsam** [comment]
Patient edit history to be shown in-line if we have time. Working on notifications for patients and users the weeks of 9/14 and 9/21
