### ISSUE TITLE
Do we want to include service specific questions in the app?

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva#28]
Not only universal questions.

**Comment by mapsam** [comment]
I'd be interested to see how this looks - but also am not confident we could get all of this information in by our next visit.

**Comment by bengolder** [comment]
I think we should aim to get Daily Planet and Access Now's separate questions in before we leave.
If possible, it would be great to add the Resource Centers (since they are included in our pre-screening).

**Comment by mapsam** [comment]
Do you propose the questions going into the patient details page?

**Comment by esmithayer** [comment]
And do we put all the questions to a specific organization in one section, or in the relevant existing section (e.g. employment) with something to denote that it's only necessary for that org? If there are questions that are required for half the organizations, the latter might make more sense.

**Comment by mapsam** [comment]
I agree. I think at one point we discussed having separate templates for other questions, such as "complete this extra section for 100% daily planet application"

**Comment by bengolder** [comment]
Yes the latter is better. We should denote the service that the question belongs to in-context.

**Comment by esmithayer** [comment]
So mockups for that?

**Comment by mapsam** [comment]
Sounds good, :+1: for in-context extra questions that should be obviously part of a specific application, and not the universal questions. 

codeforamerica/rva-screening-ui-prototypes/issues/29

**Comment by mapsam** [comment]
We have decided to include clinic-specific questions.
